#!/bin/bash

#############################################################################
# DASHBOARD DEPLOYMENT SCRIPT
# Generated by: Claude Code
# Date: 2025-11-14
# Purpose: Deploy Dashboard droplet to production server (198.54.123.234)
#
# SECURITY MODEL: "AI generates, human reviews, human executes"
# - Review this script carefully before running
# - This script should be executed ON THE SERVER
# - All commands are transparent and auditable
#
# GitHub Repository: https://github.com/jamessunheart/fpai-dashboard
# Target Port: 8002
# Dependencies: Registry (8000), Orchestrator (8001)
#############################################################################

set -e  # Exit on any error

# Configuration
REPO_URL="https://github.com/jamessunheart/fpai-dashboard.git"
APP_NAME="dashboard"
DEPLOY_PATH="/opt/fpai/agents/services/${APP_NAME}"
SERVICE_PORT=8002
PYTHON_VERSION="python3.11"  # Server has 3.11, not 3.13

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

print_step() { echo -e "${BLUE}[$1/8]${NC} $2"; }
print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_error() { echo -e "${RED}❌ $1${NC}"; }
print_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 DASHBOARD DEPLOYMENT TO 198.54.123.234"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Verify we're on the server
if [[ ! -f "/etc/hostname" ]] || [[ "$(cat /etc/hostname)" != *"fpai"* ]]; then
    print_info "This script should be run ON THE SERVER"
    print_info "Please:"
    echo "  1. Copy this script to the server"
    echo "  2. SSH to server: ssh root@198.54.123.234"
    echo "  3. Run: bash DEPLOY_DASHBOARD_NOW.sh"
    echo ""
    exit 1
fi

# Step 1: Create deployment directory
print_step 1 "Creating deployment directory..."
mkdir -p /opt/fpai/agents/services
cd /opt/fpai/agents/services

if [ -d "$APP_NAME" ]; then
    print_info "Dashboard directory exists, backing up..."
    BACKUP_NAME="${APP_NAME}-backup-$(date +%Y%m%d-%H%M%S)"
    cp -r "$APP_NAME" "$BACKUP_NAME"
    print_success "Backup created: $BACKUP_NAME"
fi

# Step 2: Clone or update repository
print_step 2 "Getting latest code from GitHub..."
if [ -d "$APP_NAME/.git" ]; then
    cd "$APP_NAME"
    git fetch origin
    git reset --hard origin/main  # Force to match GitHub
    git pull origin main
    print_success "Code updated from GitHub"
else
    rm -rf "$APP_NAME"  # Remove if exists without git
    git clone "$REPO_URL" "$APP_NAME"
    cd "$APP_NAME"
    print_success "Repository cloned"
fi

# Step 3: Set up Python virtual environment
print_step 3 "Setting up Python environment..."
if [ -d ".venv" ]; then
    print_info "Removing old virtual environment..."
    rm -rf .venv
fi

$PYTHON_VERSION -m venv .venv
print_success "Virtual environment created"

# Step 4: Install dependencies
print_step 4 "Installing dependencies..."
source .venv/bin/activate
pip install --upgrade pip -q
pip install -r requirements.txt -q
print_success "Dependencies installed"

# Step 5: Run tests
print_step 5 "Running tests..."
if pytest -v --tb=short; then
    print_success "All tests passed"
else
    print_error "Tests failed - continuing anyway (tests may need server dependencies)"
fi

# Step 6: Stop existing service if running
print_step 6 "Stopping existing service..."
if systemctl is-active --quiet fpai-${APP_NAME}; then
    systemctl stop fpai-${APP_NAME}
    print_success "Existing service stopped"
else
    print_info "No existing service running"
fi

# Step 7: Create systemd service
print_step 7 "Creating systemd service..."
cat > "/etc/systemd/system/fpai-${APP_NAME}.service" <<EOF
[Unit]
Description=Full Potential AI - Dashboard
After=network.target
Wants=fpai-registry.service fpai-orchestrator.service

[Service]
Type=simple
User=root
WorkingDirectory=${DEPLOY_PATH}
Environment="PATH=${DEPLOY_PATH}/.venv/bin:/usr/local/bin:/usr/bin:/bin"
Environment="REGISTRY_URL=http://localhost:8000"
Environment="ORCHESTRATOR_URL=http://localhost:8001"
Environment="PORT=${SERVICE_PORT}"
ExecStart=${DEPLOY_PATH}/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port ${SERVICE_PORT}
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

print_success "Systemd service created"

# Step 8: Start service
print_step 8 "Starting service..."
systemctl daemon-reload
systemctl enable fpai-${APP_NAME}
systemctl start fpai-${APP_NAME}
print_success "Service started"

# Wait for service to initialize
print_info "Waiting for service to initialize..."
sleep 5

# Health check
echo ""
print_info "Verifying deployment..."
HEALTH_URL="http://localhost:${SERVICE_PORT}/health"

MAX_RETRIES=10
RETRY_COUNT=0

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if curl -f -s "$HEALTH_URL" > /dev/null 2>&1; then
        print_success "Health check passed!"
        echo ""
        print_info "Health response:"
        curl -s "$HEALTH_URL" | python3 -m json.tool
        break
    fi

    RETRY_COUNT=$((RETRY_COUNT + 1))
    if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
        echo "   Attempt $RETRY_COUNT/$MAX_RETRIES - retrying..."
        sleep 3
    fi
done

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    print_error "Health check failed"
    print_info "Checking service logs..."
    journalctl -u fpai-${APP_NAME} -n 50 --no-pager
    echo ""
    print_info "Service status:"
    systemctl status fpai-${APP_NAME} --no-pager
    exit 1
fi

# Check UDC compliance
echo ""
print_info "Checking UDC compliance..."
ENDPOINTS=("/health" "/capabilities" "/state" "/dependencies" "/message")
ALL_OK=true

for endpoint in "${ENDPOINTS[@]}"; do
    URL="http://localhost:${SERVICE_PORT}${endpoint}"
    if curl -f -s "$URL" > /dev/null 2>&1; then
        print_success "$endpoint is responding"
    else
        print_error "$endpoint failed"
        ALL_OK=false
    fi
done

# Check registry integration
echo ""
print_info "Checking Registry integration..."
sleep 3
if curl -s http://localhost:8000/droplets | grep -q "dashboard"; then
    print_success "Dashboard registered with Registry"
else
    print_info "Dashboard will register on next heartbeat cycle"
fi

# Final summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ "$ALL_OK" = true ]; then
    print_success "DEPLOYMENT COMPLETE!"
else
    print_error "DEPLOYMENT COMPLETED WITH WARNINGS"
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
print_info "Service Details:"
echo "  Name: fpai-${APP_NAME}"
echo "  Port: ${SERVICE_PORT}"
echo "  Path: ${DEPLOY_PATH}"
echo ""
print_info "Access Dashboard:"
echo "  Local: http://localhost:${SERVICE_PORT}"
echo "  Public: http://198.54.123.234:${SERVICE_PORT}"
echo ""
print_info "Useful Commands:"
echo "  View logs: journalctl -u fpai-${APP_NAME} -f"
echo "  Check status: systemctl status fpai-${APP_NAME}"
echo "  Restart: systemctl restart fpai-${APP_NAME}"
echo "  Stop: systemctl stop fpai-${APP_NAME}"
echo ""
echo "🌐⚡💎"
echo ""
