#!/bin/bash
# Quick Start - Show top 3 actions with one command

clear
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                                                          ║"
echo "║        💎 HIGH-VALUE ACTIONS - QUICK START              ║"
echo "║                                                          ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 TOP 3 ACTIONS (Highest ROI):"
echo ""
echo "1️⃣  REDDIT OUTREACH (15 min → \$5K Week 1)"
echo "    cd agents/services/i-match && python3 execute_reddit_now.py"
echo "    Status: Needs Reddit credentials"
echo ""
echo "2️⃣  CRON MONITORING (2 min → Peace of mind)"
echo "    crontab -e  # Add overnight-guardian.sh"
echo "    Status: Ready to activate"
echo ""
echo "3️⃣  AUTONOMOUS AGENT (30 min → 24/7 growth)"
echo "    cd agents/services/i-match && python3 autonomous_outreach_agent.py"
echo "    Status: Needs Reddit + LinkedIn credentials"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 CURRENT STATUS:"
echo "  Treasury: \$139,858 (BTC + SOL)"
echo "  I MATCH: 🟢 Live"
echo "  Revenue: \$0 (15 min to first revenue)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 RECOMMENDED: Start with #1 (Reddit)"
echo "   Fastest path to validation + revenue"
echo ""
echo "📖 Full guide: cat DASHBOARD.md"
echo "📖 Detailed steps: cat _guides/activation/OUTREACH_INTEGRATION_GUIDE.md"
echo ""
