#!/bin/bash
# Auto-generated by Night Optimizer
# Monitors service health every 5 minutes

python3 /Users/jamessunheart/Development/agents/services/auto-register-services.py >> /tmp/health-monitor.log 2>&1
