#!/usr/bin/env python3
"""
Mission Spec Generator
Generates standardized mission specifications based on complexity and security levels.
"""
import argparse
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

# Configuration
MISSIONS_DIR = "missions"

SECURITY_LEVELS = {
    "low": {
        "badge": "🟢 LOW SECURITY",
        "access": "Public / Any Builder",
        "review": "Standard PR Review",
        "safeguards": "Code review, no secrets access"
    },
    "medium": {
        "badge": "🟡 MEDIUM SECURITY",
        "access": "Internal / Vetted Operators",
        "review": "Senior Operator Review",
        "safeguards": "Environment variable injection, restricted subsystem access"
    },
    "high": {
        "badge": "🔴 HIGH SECURITY",
        "access": "Architect / Owner Only",
        "review": "Architect Direct Audit",
        "safeguards": "Direct secret injection, manual confirmation, disconnected config"
    }
}

COMPLEXITY_LEVELS = {
    "simple": "Straightforward task with clear inputs and outputs. < 4 hours.",
    "moderate": "Requires integration of 2+ systems or significant logic. 1-2 days.",
    "complex": "System-wide impact, critical path, or novel architecture. 3+ days."
}

def generate_spec(
    title: str,
    goal: str,
    security: str,
    complexity: str,
    context: str,
    deliverables: List[str],
    steps: List[str],
    output_dir: str = MISSIONS_DIR
) -> str:
    """Generates a markdown mission spec."""
    
    sec_config = SECURITY_LEVELS.get(security.lower(), SECURITY_LEVELS["low"])
    comp_desc = COMPLEXITY_LEVELS.get(complexity.lower(), COMPLEXITY_LEVELS["simple"])
    
    timestamp = datetime.now().strftime("%Y-%m-%d")
    filename = f"{timestamp}-{title.lower().replace(' ', '-')}.md"
    filepath = os.path.join(output_dir, filename)
    
    md_content = f"""# MISSION: {title.upper()}

> **Status:** Available
> **Security Level:** {sec_config['badge']}
> **Complexity:** {complexity.title()} ({comp_desc})
> **Date:** {timestamp}

## 1. OBJECTIVE
{goal}

## 2. CONTEXT & ARCHITECTURE
{context}

**Security Protocols:**
- **Access:** {sec_config['access']}
- **Review:** {sec_config['review']}
- **Safeguards:** {sec_config['safeguards']}

## 3. DELIVERABLES
"""
    
    for item in deliverables:
        md_content += f"- [ ] {item}\n"
        
    md_content += f"""
## 4. EXECUTION STEPS
"""
    for i, step in enumerate(steps, 1):
        md_content += f"{i}. {step}\n"

    md_content += """
## 5. VERIFICATION
- [ ] Automated Test / Script Output
- [ ] Human Review (per security level)
- [ ] Operational Sign-off

---
*Generated by FPAI Mission Spec Generator*
"""
    
    # Ensure directory exists
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(md_content)
        
    return filepath

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate a Mission Spec")
    parser.add_argument("--title", required=True, help="Mission title")
    parser.add_argument("--goal", required=True, help="Primary objective")
    parser.add_argument("--security", choices=["low", "medium", "high"], default="low", help="Security level")
    parser.add_argument("--complexity", choices=["simple", "moderate", "complex"], default="simple", help="Complexity level")
    parser.add_argument("--context", default="Standard operational mission.", help="Background context")
    parser.add_argument("--deliverables", nargs="+", required=True, help="List of deliverables")
    parser.add_argument("--steps", nargs="+", required=True, help="Execution steps")
    
    args = parser.parse_args()
    
    path = generate_spec(
        args.title,
        args.goal,
        args.security,
        args.complexity,
        args.context,
        args.deliverables,
        args.steps
    )
    
    print(f"Mission Spec generated at: {path}")
