#!/usr/bin/env python3
"""
build_index.py — Regenerate the World Peace Agreement registry.

Scans `core/INTENT/AGREEMENTS/*.md`, parses YAML front-matter from each,
and rebuilds:
  - core/INTENT/AGREEMENTS/INDEX.md      (human-readable registry)
  - core/INTENT/AGREEMENTS/registry.json (machine-readable registry)

Source of truth: the individual Agreement files. INDEX.md and
registry.json are derived views — never edit them by hand.

Usage:
  python tools/registry/build_index.py            # regenerate
  python tools/registry/build_index.py --check    # exit 1 if files would change

Requires PyYAML (pip install pyyaml).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.stderr.write("ERROR: PyYAML not installed. Install with: pip install pyyaml\n")
    sys.exit(2)


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
AGREEMENTS_DIR = REPO_ROOT / "core" / "INTENT" / "AGREEMENTS"
INDEX_FILE = AGREEMENTS_DIR / "INDEX.md"
REGISTRY_FILE = AGREEMENTS_DIR / "registry.json"

EXCLUDE = {"INDEX.md", "README.md"}

STATUS_LABELS = {
    "active":     "🟢 Active",
    "breached":   "🔴 Breached",
    "repairing":  "🟡 Repairing",
    "repaired":   "🟢 Repaired",
    "withdrawn":  "⚪ Withdrawn",
    "archived":   "⚫ Archived",
}


def parse_frontmatter(path: Path) -> dict | None:
    """Extract YAML front-matter from a markdown file. Return None if absent or invalid."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        return None
    block = text[4:end]
    try:
        loaded = yaml.safe_load(block) or {}
        if not isinstance(loaded, dict):
            return None
        return loaded
    except yaml.YAMLError as e:
        sys.stderr.write(f"WARN: failed to parse front-matter in {path.name}: {e}\n")
        return None


def collect_agreements() -> list[dict]:
    agreements = []
    for path in sorted(AGREEMENTS_DIR.glob("*.md")):
        if path.name in EXCLUDE:
            continue
        fm = parse_frontmatter(path)
        if fm is None:
            sys.stderr.write(f"SKIP (no front-matter): {path.name}\n")
            continue
        fm["_filename"] = path.name
        agreements.append(fm)
    # most recent first
    agreements.sort(key=lambda a: str(a.get("date_formed", "")), reverse=True)
    return agreements


def render_parties(parties) -> str:
    if not parties:
        return "—"
    if not isinstance(parties, list):
        return str(parties)
    return " ↔ ".join(str(p.get("name", "?")) if isinstance(p, dict) else str(p) for p in parties)


def render_witness(witness) -> str:
    if not isinstance(witness, dict):
        return "—"
    wtype = witness.get("type", "?")
    ref = witness.get("reference", "—")
    return f"{wtype}: `{ref}`"


def truncate(s: str, n: int = 80) -> str:
    s = str(s)
    return s if len(s) <= n else s[: n - 1] + "…"


def render_table(rows: list[dict], with_witness: bool = True) -> list[str]:
    if with_witness:
        out = ["| Date | Parties | Context | Status | Witness | File |",
               "|---|---|---|---|---|---|"]
    else:
        out = ["| Date | Parties | Context | Status | File |",
               "|---|---|---|---|---|"]
    for a in rows:
        date = a.get("date_formed", "—")
        parties = render_parties(a.get("parties"))
        context = truncate(a.get("context", "—"))
        status = STATUS_LABELS.get(a.get("status"), str(a.get("status", "?")))
        filename = a["_filename"]
        link = f"[`{filename}`](./{filename})"
        if with_witness:
            witness = render_witness(a.get("witness"))
            out.append(f"| {date} | {parties} | {context} | {status} | {witness} | {link} |")
        else:
            out.append(f"| {date} | {parties} | {context} | {status} | {link} |")
    return out


def render_index_md(agreements: list[dict]) -> str:
    active = [a for a in agreements if a.get("status") == "active"]
    other = [a for a in agreements if a.get("status") != "active"]

    lines = [
        "# WORLD PEACE AGREEMENTS — REGISTRY",
        "",
        "Living index of all formed Peace Agreements under the",
        "Coherent Champions of CHRIST Manifesto v1.0.",
        "",
        f"**Count:** {len(agreements)} total · {len(active)} active · {len(other)} other",
        "**Source:** Front-matter of each `*.md` file in this directory.",
        "**Regenerate:** `python tools/registry/build_index.py`",
        "",
        "> Do not edit this file by hand. It is rebuilt from individual Agreement files.",
        "> Last-regenerated time is recorded in the git history.",
        "",
        "---",
        "",
        f"## Active Agreements ({len(active)})",
        "",
    ]
    if active:
        lines.extend(render_table(active, with_witness=True))
    else:
        lines.append("*None yet.*")

    if other:
        lines.append("")
        lines.append(f"## Other Agreements ({len(other)})")
        lines.append("")
        lines.extend(render_table(other, with_witness=False))

    lines.extend([
        "",
        "---",
        "",
        "**Statuses:** 🟢 Active · 🔴 Breached · 🟡 Repairing · 🟢 Repaired · ⚪ Withdrawn · ⚫ Archived",
        "",
        "**Public visibility:** Each Agreement may be marked `public: true` or `public: false`",
        "in front-matter. This local index lists all Agreements regardless. Public roll on",
        "`zenvillage.live` (when deployed) will only include `public: true` entries with",
        "consenting parties.",
        "",
        "**Forming a new Agreement:** see [`../FORMING_AGREEMENTS.md`](../FORMING_AGREEMENTS.md).",
        "",
    ])
    return "\n".join(lines)


def render_registry_json(agreements: list[dict]) -> str:
    cleaned = []
    for a in agreements:
        c = {k: v for k, v in a.items() if not k.startswith("_")}
        c["filename"] = a["_filename"]
        cleaned.append(c)
    payload = {
        "schema_version": 1,
        "count": len(cleaned),
        "agreements": cleaned,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False, default=str) + "\n"


def main() -> int:
    check_only = "--check" in sys.argv
    if not AGREEMENTS_DIR.exists():
        sys.stderr.write(f"ERROR: {AGREEMENTS_DIR} does not exist\n")
        return 2

    agreements = collect_agreements()
    new_index = render_index_md(agreements)
    new_registry = render_registry_json(agreements)

    if check_only:
        old_index = INDEX_FILE.read_text(encoding="utf-8") if INDEX_FILE.exists() else ""
        old_registry = REGISTRY_FILE.read_text(encoding="utf-8") if REGISTRY_FILE.exists() else ""
        if old_index != new_index or old_registry != new_registry:
            sys.stderr.write("Files would change. Run without --check to update.\n")
            return 1
        return 0

    INDEX_FILE.write_text(new_index, encoding="utf-8")
    REGISTRY_FILE.write_text(new_registry, encoding="utf-8")
    print(f"Wrote {INDEX_FILE.relative_to(REPO_ROOT)}  ({len(agreements)} agreements)")
    print(f"Wrote {REGISTRY_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
