#!/bin/bash
# Setup script for ANTHROPIC_API_KEY

echo "🔑 ANTHROPIC API KEY SETUP"
echo "=========================="
echo ""
echo "To enable content generation, you need an Anthropic API key."
echo ""
echo "Steps:"
echo "1. Go to: https://console.anthropic.com/settings/keys"
echo "2. Create a new API key"
echo "3. Copy the key (starts with 'sk-ant-api03-')"
echo ""
echo "Then run ONE of these commands:"
echo ""
echo "# Option A: Set for current session only"
echo "export ANTHROPIC_API_KEY='sk-ant-api03-YOUR_KEY_HERE'"
echo ""
echo "# Option B: Set permanently (recommended)"
echo "echo 'export ANTHROPIC_API_KEY=\"sk-ant-api03-YOUR_KEY_HERE\"' >> ~/.bashrc"
echo "source ~/.bashrc"
echo ""
echo "# Option C: Set on server"
echo "ssh root@198.54.123.234"
echo "echo 'export ANTHROPIC_API_KEY=\"sk-ant-api03-YOUR_KEY_HERE\"' >> ~/.bashrc"
echo "source ~/.bashrc"
echo ""
echo "After setting the key, run:"
echo "cd /Users/jamessunheart/Development/delegation-system"
echo "./test_content_generation.sh"
echo ""
