#!/usr/bin/env python3
"""
Scan the workspace for `papers` directories and build a markdown index.

The script intentionally keeps dependencies light so it can run anywhere the
repo is cloned. It inspects text files for philosophical keywords so M006 and
related missions can quickly find source material.
"""
from __future__ import annotations

import json
import argparse
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Iterable, List, Any, Dict

WORKSPACE_ROOT = Path(__file__).resolve().parents[2] # Fix: Should be parents[2] for core/knowledge/script
OUTPUT_MD_PATH = Path(__file__).with_name("PAPERS_INDEX.md")
# Default JSON path relative to workspace root, can be overridden
DEFAULT_JSON_PATH = WORKSPACE_ROOT / "fullpotential_ai/fullpotential_core/core/applications/website-ai/frontend/papers.json"

SCRIPT_NAME = Path(__file__).name
KEYWORDS = ["consciousism", "consciousness", "paradigm", "extractive", "regenerative"]
TEXT_EXTENSIONS = {
    ".md",
    ".txt",
    ".json",
    ".yaml",
    ".yml",
    ".py",
    ".sh",
    ".mdx",
    ".tex",
    ".rst",
}


@dataclass
class PaperEntry:
    relative_path: Path
    extension: str
    size_kb: float
    keywords: List[str]
    filename: str

    def to_row(self) -> str:
        keyword_text = ", ".join(self.keywords) if self.keywords else "–"
        return f"| `{self.relative_path}` | `{self.extension}` | {self.size_kb:>7.1f} | {keyword_text} |"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.filename.replace(".", "_").replace(" ", "_"),
            "title": self.filename.rsplit(".", 1)[0].replace("_", " ").replace("-", " ").title(),
            "filename": self.filename,
            "path": str(self.relative_path),
            "type": self.extension.strip("."),
            "size_kb": self.size_kb,
            "tags": self.keywords,
            # Link to raw file path relative to document root (assuming we deploy correctly)
            # Or link to the specific GitHub blob if we want to keep it hosted there.
            # Current issue: GitHub URLs are hardcoded to a potentially old repo structure.
            # Let's try to make them relative to the current site deployment if possible,
            # otherwise fix the GitHub URL construction.
            # For now, let's assume we want to serve them directly if they are in the repo.
            
            # If we are hosting the site ourselves, we can serve the files statically.
            # Let's construct a relative URL assuming the 'docs' folder is available at root or similar.
            # But since we are doing a quick fix for "specific files", let's just fix the GitHub link 
            # to use 'raw' if it's a PDF to trigger download/view, or 'blob' for others.
            # properly encoding spaces and special characters
            "url": f"https://github.com/jamessunheart/fpai-sessions/raw/main/{str(self.relative_path).replace(' ', '%20')}" if self.extension == ".pdf" else f"https://github.com/jamessunheart/fpai-sessions/blob/main/{str(self.relative_path).replace(' ', '%20')}"
        }


def discover_paper_dirs(root: Path) -> List[Path]:
    return sorted({p for p in root.rglob("papers") if p.is_dir()})


def detect_keywords(path: Path) -> List[str]:
    if path.suffix.lower() not in TEXT_EXTENSIONS:
        return []
    try:
        text = path.read_text(errors="ignore")
    except Exception:
        return []
    lowered = text.lower()
    return [kw for kw in KEYWORDS if kw in lowered]


def build_entries(directories: Iterable[Path]) -> List[PaperEntry]:
    entries: List[PaperEntry] = []
    for directory in directories:
        for file_path in sorted(directory.rglob("*")):
            if not file_path.is_file():
                continue
            rel_path = file_path.relative_to(WORKSPACE_ROOT)
            size_kb = round(file_path.stat().st_size / 1024, 1)
            keywords = detect_keywords(file_path)
            entries.append(
                PaperEntry(
                    relative_path=rel_path,
                    extension=file_path.suffix.lower() or "n/a",
                    size_kb=size_kb,
                    keywords=keywords,
                    filename=file_path.name
                )
            )
    return sorted(entries, key=lambda entry: entry.relative_path.as_posix())


def render_markdown(directories: List[Path], entries: List[PaperEntry]) -> str:
    header = [
        "# Papers Index",
        "",
        f"_Generated by `{SCRIPT_NAME}`. Scan roots: {len(directories)} directories, {len(entries)} files._",
        "",
        "## Roots",
    ]
    header.extend([f"- `{d.relative_to(WORKSPACE_ROOT)}`" for d in directories] or ["- _No papers directories found_"])
    header.extend(
        [
            "",
            "## Files",
            "| File | Type | Size (KB) | Keywords |",
            "| --- | --- | ---: | --- |",
        ]
    )
    rows = [entry.to_row() for entry in entries] or ["| _No files found_ |  |  |  |"]
    return "\n".join(header + rows) + "\n"


def render_json(entries: List[PaperEntry]) -> str:
    data = {
        "generated_at": "2025-11-23", # You might want to add actual timestamp generation
        "papers": [entry.to_dict() for entry in entries]
    }
    return json.dumps(data, indent=2)


def main() -> None:
    parser = argparse.ArgumentParser(description="Index research papers.")
    parser.add_argument("--json", action="store_true", help="Output JSON file for website")
    parser.add_argument("--output-json", type=Path, default=DEFAULT_JSON_PATH, help="Path to output JSON file")
    args = parser.parse_args()

    paper_dirs = discover_paper_dirs(WORKSPACE_ROOT)
    entries = build_entries(paper_dirs)
    
    OUTPUT_MD_PATH.write_text(render_markdown(paper_dirs, entries))
    print(f"Wrote {OUTPUT_MD_PATH} with {len(entries)} entries.")

    if args.json:
        json_output = render_json(entries)
        # Ensure parent directory exists
        args.output_json.parent.mkdir(parents=True, exist_ok=True)
        args.output_json.write_text(json_output)
        print(f"Wrote JSON index to {args.output_json}")


if __name__ == "__main__":
    main()

