#!/bin/bash
# Test Deployment Script - Generated by Claude Code
# Purpose: Demonstrate deployment script generation capability
# Date: 2025-11-14
#
# INSTRUCTIONS: Review this script, then run it on the server

set -e  # Exit on error

SERVER="198.54.123.234"
APP_NAME="orchestrator"
DEPLOY_PATH="/opt/fpai/apps/${APP_NAME}"
GITHUB_REPO="https://github.com/fpai-track-b/${APP_NAME}.git"

echo "=========================================="
echo "  FPAI Deployment Script - ${APP_NAME}"
echo "=========================================="
echo ""

# Step 1: Backup current version
echo "[1/6] Creating backup..."
ssh root@${SERVER} "cd ${DEPLOY_PATH} && tar -czf backup-$(date +%Y%m%d-%H%M%S).tar.gz ."

# Step 2: Pull latest from GitHub
echo "[2/6] Pulling latest code from GitHub..."
ssh root@${SERVER} "cd ${DEPLOY_PATH} && git pull origin main"

# Step 3: Install dependencies
echo "[3/6] Installing dependencies..."
ssh root@${SERVER} "cd ${DEPLOY_PATH} && source .venv/bin/activate && pip install -r requirements.txt"

# Step 4: Run tests
echo "[4/6] Running tests..."
ssh root@${SERVER} "cd ${DEPLOY_PATH} && source .venv/bin/activate && pytest test/"

# Step 5: Restart service
echo "[5/6] Restarting service..."
ssh root@${SERVER} "systemctl restart fpai-${APP_NAME}"

# Step 6: Verify health
echo "[6/6] Verifying service health..."
sleep 3
HEALTH_URL="http://${SERVER}:8001/orchestrator/health"
if curl -f -s ${HEALTH_URL} > /dev/null; then
    echo "✅ Service is healthy!"
else
    echo "❌ Service health check failed!"
    exit 1
fi

echo ""
echo "=========================================="
echo "  ✅ Deployment Complete!"
echo "=========================================="
