#!/bin/bash
# Launch First SOL Campaign - Complete Execution Script

echo "=================================================="
echo "🚀 FIRST SOL CAMPAIGN LAUNCHER"
echo "=================================================="
echo ""
echo "This script helps you execute the campaign to get"
echo "the FIRST 1 SOL donation to the church treasury."
echo ""

# Check if monitoring is already running
if pgrep -f "monitor-first-sol.py" > /dev/null; then
    echo "✅ Wallet monitoring is already running"
else
    echo "🔍 Starting wallet monitoring..."
    cd /Users/jamessunheart/Development/docs/coordination/scripts
    python3 monitor-first-sol.py &
    echo "✅ Monitoring started (running in background)"
fi

echo ""
echo "=================================================="
echo "📋 EXECUTION CHECKLIST"
echo "=================================================="
echo ""
echo "Follow the 30-minute plan in:"
echo "  /docs/coordination/outreach/EXECUTE_NOW_FIRST_SOL.md"
echo ""
echo "Quick Summary:"
echo ""
echo "⏱️  MINUTES 0-10: Personal Outreach"
echo "   → Text/DM 5 people with SOL wallets"
echo "   → Use template from EXECUTE_NOW_FIRST_SOL.md"
echo ""
echo "⏱️  MINUTES 10-15: Reddit Post"
echo "   → Post to r/solana"
echo "   → Title: \"Challenge: Send 1 SOL to this AI church treasury...\""
echo ""
echo "⏱️  MINUTES 15-20: Twitter Post"
echo "   → Tweet the challenge"
echo "   → Tag @solana if feeling bold"
echo ""
echo "⏱️  MINUTES 20-25: Discord Servers"
echo "   → Post in 3 Solana Discord servers"
echo "   → Use template from EXECUTE_NOW_FIRST_SOL.md"
echo ""
echo "⏱️  MINUTES 25-30: Follow Up"
echo "   → Engage with ALL comments/replies"
echo "   → Answer questions immediately"
echo ""
echo "=================================================="
echo "💰 CHURCH TREASURY ADDRESS"
echo "=================================================="
echo ""
echo "FLfNDVLD2vDQdTjMFSt1xJivhr8pKASwEBzRYHZRU7db"
echo ""
echo "Explorer:"
echo "https://explorer.solana.com/address/FLfNDVLD2vDQdTjMFSt1xJivhr8pKASwEBzRYHZRU7db"
echo ""
echo "=================================================="
echo "🎉 WHEN FIRST SOL ARRIVES"
echo "=================================================="
echo ""
echo "The monitor will alert you automatically!"
echo ""
echo "Then immediately:"
echo "1. Open CELEBRATION_TEMPLATES.md"
echo "2. Copy/paste celebration posts"
echo "3. Post to Reddit, Twitter, Discord within 5 minutes"
echo "4. DM the sender to thank them"
echo "5. This triggers the FOMO flywheel!"
echo ""
echo "=================================================="
echo "📁 KEY FILES"
echo "=================================================="
echo ""
echo "Execution plan:"
echo "  /docs/coordination/outreach/EXECUTE_NOW_FIRST_SOL.md"
echo ""
echo "Celebration templates (use when SOL arrives):"
echo "  /docs/coordination/outreach/CELEBRATION_TEMPLATES.md"
echo ""
echo "Full campaign materials:"
echo "  /docs/coordination/outreach/FIRST_SOL_CAMPAIGN.md"
echo ""
echo "Support page (share this URL):"
echo "  http://198.54.123.234:8401/support"
echo ""
echo "=================================================="
echo "⚡ READY TO EXECUTE"
echo "=================================================="
echo ""
echo "The monitoring is running. Now you need to execute"
echo "the outreach. Open the execution plan and GO:"
echo ""
echo "  cat /Users/jamessunheart/Development/docs/coordination/outreach/EXECUTE_NOW_FIRST_SOL.md"
echo ""
echo "Good luck! 🚀"
echo ""
